'use client';

import { use, useState } from 'react';
import dynamic from 'next/dynamic';
import { FileTree } from '@/components/code/file-tree';
import { CodeDiff } from '@/components/code/code-diff';
import { Terminal } from '@/components/code/terminal';
import { Spinner } from '@/components/ui/spinner';
import { cn } from '@/lib/utils';
import type { ProjectFile } from '@/types';

// Dynamically import Monaco editor to avoid SSR issues
const CodeEditor = dynamic(
  () => import('@/components/code/code-editor').then((mod) => mod.CodeEditor),
  {
    ssr: false,
    loading: () => (
      <div className="flex items-center justify-center h-full">
        <Spinner size="lg" />
      </div>
    ),
  }
);

// Mock file tree
const mockFiles: ProjectFile[] = [
  {
    id: 'f1',
    projectId: 'proj-1',
    name: 'src',
    path: 'src',
    type: 'directory',
    lastModified: '',
    children: [
      {
        id: 'f2',
        projectId: 'proj-1',
        name: 'index.ts',
        path: 'src/index.ts',
        type: 'file',
        language: 'typescript',
        lastModified: '',
      },
      {
        id: 'f3',
        projectId: 'proj-1',
        name: 'app.ts',
        path: 'src/app.ts',
        type: 'file',
        language: 'typescript',
        lastModified: '',
      },
      {
        id: 'f4',
        projectId: 'proj-1',
        name: 'routes',
        path: 'src/routes',
        type: 'directory',
        lastModified: '',
        children: [
          {
            id: 'f5',
            projectId: 'proj-1',
            name: 'auth.ts',
            path: 'src/routes/auth.ts',
            type: 'file',
            language: 'typescript',
            lastModified: '',
          },
        ],
      },
    ],
  },
  {
    id: 'f6',
    projectId: 'proj-1',
    name: 'package.json',
    path: 'package.json',
    type: 'file',
    language: 'json',
    lastModified: '',
  },
];

type ViewMode = 'editor' | 'diff';

export default function CodePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const [activeFile, setActiveFile] = useState<ProjectFile | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>('editor');

  const sampleCode = `import express from 'express';
import cors from 'cors';
import { authRouter } from './routes/auth';

const app = express();

app.use(cors());
app.use(express.json());

app.use('/api/auth', authRouter);

app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

export default app;
`;

  const oldCode = `import express from 'express';
import { authRouter } from './routes/auth';

const app = express();

app.use(express.json());
app.use('/api/auth', authRouter);

export default app;`;

  return (
    <div className="space-y-4">
      {/* Page header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Code</h1>
          <p className="text-sm text-zinc-400 mt-1">
            Browse, edit, and review code generated by agents
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setViewMode('editor')}
            className={cn(
              'px-3 py-1.5 rounded-lg text-sm transition-colors',
              viewMode === 'editor'
                ? 'bg-brand-600 text-white'
                : 'text-zinc-400 hover:text-white hover:bg-surface-2'
            )}
          >
            Editor
          </button>
          <button
            onClick={() => setViewMode('diff')}
            className={cn(
              'px-3 py-1.5 rounded-lg text-sm transition-colors',
              viewMode === 'diff'
                ? 'bg-brand-600 text-white'
                : 'text-zinc-400 hover:text-white hover:bg-surface-2'
            )}
          >
            Diff
          </button>
        </div>
      </div>

      {/* Main content */}
      <div className="flex gap-4 h-[calc(100vh-240px)]">
        {/* File tree */}
        <div className="w-60 flex-shrink-0 bg-surface-1 border border-surface-3 rounded-xl overflow-y-auto scrollbar-thin">
          <div className="px-4 py-3 border-b border-surface-3">
            <h2 className="text-sm font-medium text-white">Files</h2>
          </div>
          <FileTree
            files={mockFiles}
            onFileSelect={setActiveFile}
            activeFilePath={activeFile?.path}
          />
        </div>

        {/* Editor area */}
        <div className="flex-1 flex flex-col gap-4">
          {viewMode === 'editor' ? (
            <div className="flex-1 bg-surface-1 border border-surface-3 rounded-xl overflow-hidden">
              {activeFile ? (
                <CodeEditor
                  fileId={activeFile.id}
                  language={activeFile.language ?? 'typescript'}
                  initialValue={sampleCode}
                />
              ) : (
                <div className="flex items-center justify-center h-full text-zinc-500 text-sm">
                  Select a file from the tree to start editing
                </div>
              )}
            </div>
          ) : (
            <div className="flex-1 overflow-auto">
              <CodeDiff
                oldCode={oldCode}
                newCode={sampleCode}
                fileName={activeFile?.name ?? 'app.ts'}
              />
            </div>
          )}

          {/* Terminal */}
          <Terminal projectId={id} className="flex-shrink-0" />
        </div>
      </div>
    </div>
  );
}
