package com.deepagent.orchestrator.grpc;

import com.deepagent.orchestrator.dto.AgentTaskResponse;
import io.grpc.ManagedChannel;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * gRPC client for communicating with the Python agent service.
 *
 * <p><strong>NOT FUNCTIONAL.</strong> The protobuf/gRPC stubs are never
 * generated by this build: {@code src/main/proto} does not exist and the only
 * proto file lives at {@code src/main/resources/proto/agent_service.proto},
 * which the {@code protobuf-maven-plugin} does not treat as a compile input
 * (it is packaged as a classpath resource instead). Consequently no
 * {@code AgentServiceGrpc} / {@code *OuterClass} types exist and there is
 * nothing to call.</p>
 *
 * <p>This class therefore fails loudly instead of pretending to work. The
 * previous implementation returned a fabricated
 * {@code AgentTaskResponse.completed(..., "Agent execution completed
 * (placeholder)")} and emitted three synthetic streaming chunks, which made
 * every execution look successful while nothing ever reached the agent
 * runtime. Real agent execution goes through
 * {@link com.deepagent.orchestrator.client.AgentRestClient} (HTTP) instead.</p>
 *
 * <p>To make this class real: move the proto to {@code src/main/proto} and
 * configure the {@code protobuf-maven-plugin} {@code protoSourceRoot}
 * accordingly, then replace the two throwing methods with generated stub
 * invocations.</p>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class AgentServiceGrpcClient {

    /** Message used by every unimplemented method: it names the missing artifact. */
    private static final String NOT_GENERATED =
            "gRPC agent-service stub is not generated: src/main/proto is missing and "
                    + "src/main/resources/proto/agent_service.proto is not compiled by the "
                    + "protobuf-maven-plugin, so no AgentServiceGrpc stub exists. Use "
                    + "AgentRestClient (HTTP) for agent execution, or move the proto to "
                    + "src/main/proto and configure protoSourceRoot.";

    private final ManagedChannel agentServiceChannel;

    /**
     * Submits a task to the Python agent service synchronously.
     *
     * @param projectId the project ID
     * @param taskId    the task ID
     * @param agentType the type of agent to invoke
     * @param input     the task input data
     * @return the agent task response with output
     * @throws UnsupportedOperationException always - the gRPC stub is not generated
     */
    public AgentTaskResponse submitTask(Long projectId, Long taskId,
                                         String agentType, String input) {
        log.error("submitTask called but the gRPC stub is not generated: projectId={}, taskId={}, agentType={}",
                projectId, taskId, agentType);
        throw new UnsupportedOperationException(NOT_GENERATED);
    }

    /**
     * Submits a task with server-side streaming for real-time output.
     *
     * @param projectId     the project ID
     * @param taskId        the task ID
     * @param agentType     the type of agent to invoke
     * @param input         the task input data
     * @param outputHandler callback for processing each output chunk
     * @throws UnsupportedOperationException always - the gRPC stub is not generated
     */
    public void submitTaskStream(Long projectId, Long taskId,
                                  String agentType, String input,
                                  java.util.function.Consumer<String> outputHandler) {
        log.error("submitTaskStream called but the gRPC stub is not generated: projectId={}, taskId={}, agentType={}",
                projectId, taskId, agentType);
        throw new UnsupportedOperationException(NOT_GENERATED);
    }

    /**
     * Checks the health of the agent service connection.
     *
     * <p>This only reports the state of the (unused) managed channel; it does
     * not prove that the agent runtime is functional, because no RPC is ever
     * issued over it.</p>
     *
     * @return true if the channel has not reached a terminal state
     */
    public boolean isHealthy() {
        try {
            var state = agentServiceChannel.getState(false);
            return !state.isTerminalState();
        } catch (Exception e) {
            log.warn("Agent service health check failed: {}", e.getMessage());
            return false;
        }
    }
}
