"""Shared state definition for the LangGraph workflow.

Uses TypedDict for type-safe state management across graph nodes.
"""

from typing import Any, TypedDict


class WorkflowState(TypedDict, total=False):
    """Shared state that flows through the LangGraph workflow.

    This state is passed between nodes and accumulates results
    as the workflow progresses through the agent DAG.

    Attributes:
        task: The original task description.
        context: Additional context provided with the task.
        current_agent: The name of the currently executing agent.
        plan: The execution plan generated by the planning phase.
        code_output: Code generated by the Coder agent.
        review_output: Review feedback from the Reviewer agent.
        test_output: Test code generated by the Tester agent.
        deploy_output: Deployment config from the Deployer agent.
        messages: Conversation history across all agents.
        artifacts: Accumulated artifacts from all agents.
        errors: Any errors encountered during execution.
        iteration: Current iteration count for retry loops.
        max_iterations: Maximum allowed iterations.
        status: Current workflow status.
    """

    # Input
    task: str
    context: dict[str, Any]

    # Execution tracking
    current_agent: str
    iteration: int
    max_iterations: int
    status: str

    # Agent outputs
    plan: str
    code_output: str
    review_output: str
    test_output: str
    deploy_output: str

    # Shared data
    messages: list[dict[str, Any]]
    artifacts: list[dict[str, Any]]
    errors: list[str]


def create_initial_state(task: str, context: dict[str, Any] | None = None) -> WorkflowState:
    """Create an initial workflow state for a new task.

    Args:
        task: The task description to execute.
        context: Optional additional context.

    Returns:
        A WorkflowState with default initial values.
    """
    return WorkflowState(
        task=task,
        context=context or {},
        current_agent="",
        iteration=0,
        max_iterations=3,
        status="pending",
        plan="",
        code_output="",
        review_output="",
        test_output="",
        deploy_output="",
        messages=[],
        artifacts=[],
        errors=[],
    )
